services:
  web-server:
    build: 
      context: ./docker/php/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
      - ./source:/var/www/html/source
    depends_on:
      - my-database
    networks:
      - kantin-network
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_PORT: ${DB_PORT}

  my-database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kantin-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: my-database
    depends_on:
      - my-database
    networks:
      - kantin-network
  
  # nyalakan jika pake tunnel:p,khusus eqki tapi maybe kayaknya
  # cloudflare-tunnel:
  #   image: cloudflare/cloudflared:latest
  #   restart: always
  #   volumes:
  #     # Mengintip langsung folder .cloudflared asli di Windows lu (Ganti 'Administrator' sesuai user PC-mu jika beda)
  #     - C:\Users\Administrator\.cloudflared:/home/nonroot/.cloudflared
  #     - C:\Users\user\.cloudflared:/home/nonroot/.cloudflared
  #     - 
  #     
  #   # Tembak langsung file credentials (.json) yang ada di dalam volume tadi
  #   command: tunnel --credentials-file /home/nonroot/.cloudflared/5da79a10-29af-44d5-ba4e-84baa3f5654a.json run --url http://web-server:80 5da79a10-29af-44d5-ba4e-84baa3f5654a
  #   networks:
  #     - kantin-network

  cloudflare-tunnel:
      image: cloudflare/cloudflared:latest
      profiles: ["tunnel-aktif"] 
      restart: always
      environment:
        - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
      command: tunnel run
      networks:
        - kantin-network


networks:
  kantin-network:
    driver: bridge